{% set name = "libsimpleitk" %}
{% set version = "2.1.0" %}
{% set sha256 = "a551636e5d33dff88818bdb2fdaba190184b225d0eee015bfa2ce3a4fb6bdb24" %}


{% set test_cmake_args = "-D \"CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=${PREFIX}\" ./Examples" %}  # [not win]
{% set test_cmake_args = "-D \"CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=%PREFIX%\" ./Examples" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SimpleITK/SimpleITK/releases/download/v{{ version }}/SimpleITK-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    -  0001-Remove-forward-declaration-of-Image-of-deque.patch

build:
  number: 2
  skip: true  # [ win and py27]

requirements:
  build:
    - cmake   >=3.15
    - ninja
    - lua     5.3.*
    - swig    4.0.*
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - libitk-devel  5.2.*

  run:
    - vs2015_runtime  # [win]
    - {{ pin_compatible('libitk-devel', exact=True) }}

test:
  requires:
    - cmake
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  source_files:
    - Examples
  commands:
    - test -d $PREFIX/include/SimpleITK*                                 # [not win]
    - if not exist %LIBRARY_INC%\\SimpleITK* exit 1                      # [win]
    - cmake -D "CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=${PREFIX}" ./Examples  # [not win]
    - cmake --build . --config Release                                   # [not win]

about:
  home: http::/www.simpleitk.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Development headers and libraries for SimpleITK a simplified interface to the Insight Toolkit.

extra:
  recipe-maintainers:
    - blowekamp
    - zivy
