conda_forge_output_validation: true
build_platform:
  osx_arm64: osx_64
linux_aarch64:
  enabled: false
linux_ppc64le:
  enabled: false
test_on_native_only: true
github:
  branch_name: main
  tooling_branch_name: main
